[profile.default]
src = "src"
script = "script"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
remappings = [
  "@uniswap/v2-core/=lib/v2-core/",
  "@uniswap/v2-periphery/=lib/v2-periphery/",
  "@uniswap/lib/=lib/uniswap-lib/",
  "forge-std/=lib/forge-std/src/",
  "weth9/=lib/weth9/contracts/"
]
